grails-app/controllers/ishareserver/InstitutionController.groovy
package ishareserver

import grails.converters.JSON

import java.text.SimpleDateFormat

class InstitutionController {
	def amazonWebService
	def institutionDynaService
	
	
    def index() { 
		switch(request.method){
			case "POST":
				def jsonObj = request.JSON
				
				def dateFormatter = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'");
				//dateFormatter.setTimeZone(TimeZone.getTimeZone("PRC"));
				
				Calendar cins = Calendar.getInstance();
				TimeZone tz  = TimeZone.getTimeZone("PRC");
				cins.setTimeZone(tz);
				
				def date = cins.getTime()
				def prcTimeNow = dateFormatter.format(date);
				
				jsonObj.createTime = prcTimeNow
				
				def institution = new Institution(jsonObj)
				
				//amazonWebService.dynamoDBMapper.save(institution)
				institutionDynaService.saveInstitution(institution)
				
				render institution as JSON
				
				
			break
			
			
			case "GET":
				
				def name  = params.name
				def areaTypeCode =  params.areaTypeCode
				def filter = params.filter
				def res
				if(filter == null){
					res = institutionDynaService.loadInstitutionByATN(areaTypeCode, name)
					
				}else if(filter.equals("fourGet")){
					// just area code without type code
					res = institutionDynaService.getFourRandomInstitution(areaTypeCode)
				}else{
					res = institutionDynaService.queryInstitutionsByPartOfName(areaTypeCode, name)
				}
				
				
				render res as JSON
			break
			
			
			case "PUT":
				def jsonObj = request.JSON
				
				
				def institution = new Institution(jsonObj)
				
				institutionDynaService.saveInstitution(institution)
				
				render institution as JSON
			
			break
			
			
			case "DELETE":
				def name  = params.name
				def areaTypeCode =  params.areaTypeCode
				institutionDynaService.deleteInstitution(areaTypeCode, name)
				render "successfull"
			break
		}
	}
}

grails-app/controllers/ishareserver/InstitutionTypeController.groovy
package ishareserver



import static org.springframework.http.HttpStatus.*
import com.amazonaws.services.ec2.model.Instance
import com.amazonaws.services.ec2.model.Reservation
import grails.converters.JSON
import grails.transaction.Transactional
import redis.clients.jedis.Jedis


class InstitutionTypeController {
	def amazonWebService
    //static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]
	def jedisConPoolService
	def queueDynaService
	
    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
	
		
		def institutionTypeInstance = new InstitutionType();
		//def institutionTypeInstance = Hello.newInstance([typeId:1, typeName:'hospital']);
		//institutionTypeInstance.setVariable("typeId", 1);
		def inst = amazonWebService.dynamoDBMapper.load(InstitutionType.class,3)
		//Jedis jed  = jedisConPoolService.getPool().getResource()
		//jed.set("hello","hello ,jedis!")
		//println"${jed.get("hello")}"
		
		//queueDynaService.redisExpireTest()
		
		render inst as JSON;
		
		/*
		institutionTypeInstance.typeId = 5
		institutionTypeInstance.typeName = "test"
		println institutionTypeInstance.typeName
		amazonWebService.dynamoDBMapper.save(institutionTypeInstance)
		*/

		/*
		List reservations = amazonWebService.ec2.describeInstances().reservations
		reservations.each { Reservation reservation ->
			println "reservationId: ${reservation.reservationId}"
			reservation.instances.each() { Instance instance ->
				println "instanceId: ${instance.instanceId}, imageId: ${instance.imageId}, instanceType: ${instance.instanceType}"
			}
		}
		*/
		
       // respond InstitutionType.list(params), model:[institutionTypeInstanceCount: InstitutionType.count()]
    }

}

grails-app/controllers/ishareserver/MainPageController.groovy
package ishareserver


class MainPageController {

    def index() { 
		
		//def uri = this.getClass().getResource("/grails-app/views/mainPage").file;
		//println "${uri}"
		
	
//		def mainPageP =  grailsApplication.parentContext.getResource("WEB-INF/grails-app/views/mainPage").file
//		println "${mainPageP}"
	
		
		//def htmlContent = new File(uri,'paiduihaoIndex.html').text
	//	render text: htmlContent, contentType:"text/html", encoding:"UTF-8"
	//	render(view: "paiduihaoIndex",model: [name:"${uri}"])
		render(view: "paiduihaoIndex")
	}
}

grails-app/controllers/ishareserver/QueueController.groovy
package ishareserver

import grails.converters.JSON
import java.text.SimpleDateFormat

class QueueController {
	def queueDynaService
	
    def index() { 
		switch(request.method){
			case "POST":
			
			break;
			
			case "GET":
				def insATN  = params.insATN
				QueueStatus qs = queueDynaService.getQueueStatus(insATN)
				render qs as JSON
			
			break;
			
			case "PUT":
				def jsonObj = request.JSON
				def dateFormatter = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'");
				
				Calendar cins = Calendar.getInstance();
				TimeZone tz  = TimeZone.getTimeZone("PRC");
				cins.setTimeZone(tz);
				
				def date = cins.getTime()
				def prcTimeNow = dateFormatter.format(date);
				
				jsonObj.commitTime = prcTimeNow
				
				QueueRecord qrec= new QueueRecord(jsonObj)
				QueueStatus qs = queueDynaService.updateQueue(qrec)
				render qs as JSON
				
			break;
			
			case "DELETE":
			
			break;
		}
		
	}
}

grails-app/controllers/ishareserver/UserController.groovy
package ishareserver

import grails.converters.JSON

class UserController {
	def userDynaService
	
    def index() {
		
		switch(request.method){
			case "GET":
			def msisdn  = params.msisdn
			def name = params.nickName
			User user  = userDynaService.loadUser(msisdn)

			render user as JSON
		
		break;
		}
	}
	
	def login(){
		
		switch(request.method){
			case "POST":
			
			break;
			
			case "GET":
				def msisdn  = params.msisdn
				def name = params.nickName
				User user  = userDynaService.loginUser(msisdn, name)
				
				render user as JSON
			
			break;
			
			case "PUT":

			break;
			
			case "DELETE":
			
			break;
		}
	}
}

grails-app/views/institutionType/_form.gsp
<%@ page import="ishareserver.InstitutionType" %>



<div class="fieldcontain ${hasErrors(bean: institutionTypeInstance, field: 'typeId', 'error')} ">
	<label for="typeId">
		<g:message code="institutionType.typeId.label" default="Type Id" />
		
	</label>
	<g:field type="number" name="typeId" value="${institutionTypeInstance.typeId}" />

</div>

<div class="fieldcontain ${hasErrors(bean: institutionTypeInstance, field: 'typeName', 'error')} ">
	<label for="typeName">
		<g:message code="institutionType.typeName.label" default="Type Name" />
		
	</label>
	<g:textField name="typeName" value="${institutionTypeInstance?.typeName}" />

</div>

grails-app/views/institutionType/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'institutionType.label', default: 'InstitutionType')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-institutionType" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-institutionType" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${institutionTypeInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${institutionTypeInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:institutionTypeInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/institutionType/edit.gsp
<%@ page import="ishareserver.InstitutionType" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'institutionType.label', default: 'InstitutionType')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-institutionType" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-institutionType" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${institutionTypeInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${institutionTypeInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:institutionTypeInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${institutionTypeInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/institutionType/index.gsp
<%@ page import="ishareserver.InstitutionType" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'institutionType.label', default: 'InstitutionType')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-institutionType" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-institutionType" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="typeId" title="${message(code: 'institutionType.typeId.label', default: 'Type Id')}" />
					
						<g:sortableColumn property="typeName" title="${message(code: 'institutionType.typeName.label', default: 'Type Name')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${institutionTypeInstanceList}" status="i" var="institutionTypeInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${institutionTypeInstance.id}">${fieldValue(bean: institutionTypeInstance, field: "typeId")}</g:link></td>
					
						<td>${fieldValue(bean: institutionTypeInstance, field: "typeName")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${institutionTypeInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/institutionType/show.gsp
<%@ page import="ishareserver.InstitutionType" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'institutionType.label', default: 'InstitutionType')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-institutionType" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-institutionType" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list institutionType">
			
				<g:if test="${institutionTypeInstance?.typeId}">
				<li class="fieldcontain">
					<span id="typeId-label" class="property-label"><g:message code="institutionType.typeId.label" default="Type Id" /></span>
					
						<span class="property-value" aria-labelledby="typeId-label"><g:fieldValue bean="${institutionTypeInstance}" field="typeId"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${institutionTypeInstance?.typeName}">
				<li class="fieldcontain">
					<span id="typeName-label" class="property-label"><g:message code="institutionType.typeName.label" default="Type Name" /></span>
					
						<span class="property-value" aria-labelledby="typeName-label"><g:fieldValue bean="${institutionTypeInstance}" field="typeName"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:institutionTypeInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${institutionTypeInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/layouts/main.gsp
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"><!--<![endif]-->
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title><g:layoutTitle default="Grails"/></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="shortcut icon" href="${assetPath(src: 'favicon.ico')}" type="image/x-icon">
		<link rel="apple-touch-icon" href="${assetPath(src: 'apple-touch-icon.png')}">
		<link rel="apple-touch-icon" sizes="114x114" href="${assetPath(src: 'apple-touch-icon-retina.png')}">
  		<asset:stylesheet src="application.css"/>
		<asset:javascript src="application.js"/>
		<g:layoutHead/>
	</head>
	<body>
		<div id="grailsLogo" role="banner"><a href="http://grails.org"><asset:image src="grails_logo.png" alt="Grails"/></a></div>
		<g:layoutBody/>
		<div class="footer" role="contentinfo"></div>
		<div id="spinner" class="spinner" style="display:none;"><g:message code="spinner.alt" default="Loading&hellip;"/></div>
	</body>
</html>

grails-app/views/mainPage/paiduihaoIndex.gsp
<!DOCTYPE html>

<html ng-app="eleme" perf-error="desktop/home/" class="ng-scope"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><style type="text/css">@charset "UTF-8";[ng\:cloak],[ng-cloak],[data-ng-cloak],[x-ng-cloak],.ng-cloak,.x-ng-cloak,.ng-hide{display:none !important;}ng\:form{display:block;}.ng-animate-block-transitions{transition:0s all!important;-webkit-transition:0s all!important;}.ng-hide-add-active,.ng-hide-remove{display:block!important;}</style><style type="text/css">@charset "UTF-8";[ng\:cloak],[ng-cloak],[data-ng-cloak],[x-ng-cloak],.ng-cloak,.x-ng-cloak,.ng-hide{display:none !important;}ng\:form{display:block;}.ng-animate-block-transitions{transition:0s all!important;-webkit-transition:0s all!important;}.ng-hide-add-active,.ng-hide-remove{display:block!important;}</style>
    <meta charset="utf-8">
    <meta name="renderer" content="webkit">
    

    <title ng-bind="SEO.title" class="ng-binding">排队号</title>
 
    <meta name="format-detection" content="telephone=no, email=no">


    <meta property="qc:admins" content="2263606250655">

	<link rel="stylesheet" href="${resource(dir: 'css', file: 'vendor.9d73b7.css')}" type="text/css">
	<link rel="stylesheet" href="${resource(dir: 'css', file: 'home.925596.css')}" type="text/css">
    
    <script src="${resource(dir: 'js', file: 'perf.js')}" type="text/javascript"></script>
    <%--<script src="${resource(dir: 'js', file: 'endor.953c61.js')}" type="text/javascript"></script>
    <script src="${resource(dir: 'js', file: 'home.0fad37.js')}" type="text/javascript"></script>

    

    --%><!--<base href="/home/">--><!--<base href=".">--><base href=".">
  <meta name="mobile-agent" content="undefined">
  <meta name="description" content="">
  <meta name="keywords" content="排队号"></head>
  <body ie8wide="" cute-title="" ng-class="{hidesidebar: layoutState &amp;&amp; layoutState.hideSidebar, smallbody: layoutState.smallBody, whitebody: layoutState.whiteBody}" class="hidesidebar smallbody whitebody" ryt14370="1">
  
    <!-- ngView:  --><div ng-view="" role="main" class="ng-scope"><div class="map ng-scope" ng-class="{mapmode: mapMode}"><div class="container"><div class="map-main ng-isolate-scope" ng-class="{mapmode: mapMode}" map-main="" map-mode="mapMode"><h2 class="map-logo"> 排队 无忧
</h2><div class="map-content"></div></div><div class="mapfooter" map-footer=""><div class="mapfooter-app"><div class="mapfooter-app-image"><img src="${resource(dir: 'images', file: '1456991852.png')}" alt="扫码下载 APP"> <span>扫码下载 APP</span></div><div class="mapfooter-app-text"><p>Android 扫码下载</p><strong>轻松</strong><strong class="color-stress">排队</strong><p>ios版 期待中</p></div></div></div></div></div></div>
  
  

</body></html>